set ::env(PDK) "sky130A"
set ::env(PDKPATH) "/home/erinc/.volare/sky130A"
set ::env(STD_CELL_LIBRARY) "sky130_fd_sc_hd"
set ::env(SCLPATH) "/home/erinc/.volare/sky130A/sky130_fd_sc_hd"
set ::env(DESIGN_DIR) "/openlane/designs/piped"
set ::env(//) "Tecnhology-Specific Configs"
set ::env(DESIGN_NAME) "CorePipelinedWithoutMemory"
set ::env(VERILOG_FILES) "/openlane/designs/piped/src/ALU.v /openlane/designs/piped/src/mem_1r1w_sram.v /openlane/designs/piped/src/ConditionCheck.v /openlane/designs/piped/src/RegFile.v /openlane/designs/piped/src/DecodeStagePipelined.v /openlane/designs/piped/src/DataMemWithoutMem.v /openlane/designs/piped/src/MemoryCoreWrapper.v /openlane/designs/piped/src/InstTypeDecoder.v /openlane/designs/piped/src/Shifter.v /openlane/designs/piped/src/ImmExtender.v /openlane/designs/piped/src/MemStageWithoutMemory.v /openlane/designs/piped/src/FetchStageWithoutImem.v /openlane/designs/piped/src/Adder.v /openlane/designs/piped/src/FlipFlop.v /openlane/designs/piped/src/ExecuteStagePipelined.v /openlane/designs/piped/src/CorePipelinedWithoutMemory.v /openlane/designs/piped/src/WriteBackStage.v /openlane/designs/piped/src/HazardControlUnit.v"
set ::env(CLOCK_PERIOD) "6"
set ::env(CLOCK_PORT) "clk"
set ::env(SYNTH_STRATEGY) "DELAY 4"
set ::env(FP_CORE_UTIL) "30"
